puppetlabs/rspec-puppet

CHANGELOG.md, docs/changelog/index.md, rspec-puppet.gemspec
[rspec-puppet.com](rspec-puppet.com) will continue to point at the original rodjek namespace. As such changes to `/docs` have not been made.
=> (GH-5) Release prep for 2.10.0

README.md, lib/rspec-puppet.rb, lib/rspec-puppet/adapters.rb, lib/rspec-puppet/facter_impl.rb, lib/rspec-puppet/support.rb, spec/unit/adapters_spec.rb, spec/unit/facter_impl_spec.rb
Starting with versions 7.12.0/6.25.0, Puppet was changed not to directly
depend on Facter anymore, but to use a `Puppet::Runtime` implementation
instead (e.g. calls to `Facter` were changed to
`Puppet.runtime[:facter]` to allow for pluggable Facter backends).
rspec-puppet stubs facts from facterdb by setting custom facts with
higher weights, meaning that Facter 4 will still resolve the underlying
core facts (which is by design), leading to noticeable performance hits
when compiling catalogs with Facter 4 as opposed to Facter 2 (which just
returned the custom fact).
This means we can achieve a pretty big performance improvement with
rspec-puppet by registering a custom Facter implementation that bypasses
Facter altogether and just saves facts to hash.
This behavior cand be activated by …
=> Add setting to use custom Facter implementation

lib/rspec-puppet.rb, lib/rspec-puppet/adapters.rb, spec/unit/adapters_spec.rb
Using the 'rspec' facter implementation we could sometimes get in a case where the values of `FacterImpl` and `Puppet.runtime[:facter]` diverged between example groups.
Because rspec-puppet overrides facts using the `FacterImpl` constant (which is only set once), `Puppet.runtime[:facter]` would point to a different instance of `FacterTestImpl` with no available facts, causing calls to `Puppet.runtime[:facter].value` to fail.
To prevent this from happening, attempt to set `Puppet.runtime[:facter]` to the value of `FacterImpl` if available, this way we make sure `Puppet.runtime[:facter]` and `FacterImpl` operate on the same instance of `FacterTestImpl`.
=> Ensure FacterImpl consistency between example groups

lib/rspec-puppet/matchers/run.rb
This allows you to check the return type of functions, like this
example:
```
is_expected.to run.with_params('mymod/template.epp', { 'foo' => 'bar' }).and_return(kind_of String)
```
=> Add the ability to use `kind_of` matchers

CODEOWNERS
Prior to this commit the CODEOWNERS file for this repository did not exist.
Since the efforts of this team have been merged in to CaT (modules) this
commit adds the associated group to https://github.com/orgs/puppetlabs/teams/modules.
=> (GH-CAT-98) - Adding CODEOWNERS file

README.md
There is no example of sensitive in that docs and its not necessarily obvious the helper exists
=> Update README.md to include sensitive function

Gemfile
Puppet 4 and Facter 2 fail to install on a current Ruby version. It's also not very interesting since they're unsupported.
=> Default to current versions of Puppet and Facter

README.md
The previous example wasn't clear to me, as someone who's not a Ruby dev. It took a bit of head scratching to work out what was going on. Hopefully this is more clear.
=> Clarify function testing parser scope section

lib/rspec-puppet/facter_impl.rb, spec/unit/facter_impl_spec.rb
In Puppet 8, core providers are being confined using facts fetched using 'dot-notation'. We need to support this style of lookup in our stub implementation.
For example in `lib/puppet/provider/service/init.rb`
```ruby
confine :true => begin
os = Puppet.runtime[:facter].value(:operatingsystem).downcase
```
was updated to
```ruby
confine :true => begin
os = Puppet.runtime[:facter].value('os.name').downcase
```
See
https://github.com/puppetlabs/puppet/commit/82cef2371352b648cc60aa7b7cedaa973c38ad35 for Puppet 8 change.
Relates to puppetlabs/rspec-puppet#38
=> Support dot-notation when retrieving facts in facter_impl

.github/workflows/ci.yml, .github/workflows/nightly.yml, Gemfile
For CI and to keep in line with modules, we should use `*_GEM_VERSION` environment variables in the gem file.
=> (MAINT) Fix gem env vars

docs/_includes/catalogue_matchers.md
I was searching how to test sensitive things. I found this is possible into CHANGELOG. It looks interesting to report this into docs.
=> doc : add information about sensitive helper

lib/rspec-puppet/support.rb
In 4ef2f3643eaab642d2f24ffda6a507699d9ae0a8 this was added as a workaround, but in 48c56051047667ff6f7f3915d7597e2da669e26d a custom Facter implementation was added. This avoids any calls to the real Facter and doesn't suffer from the issue where it was attempting to load Windows gems on Linux.
Fixes #15
=> Avoid hardcoding ipaddress6 default

Rakefile, lib/rspec-puppet/monkey_patches.rb, lib/rspec-puppet/support.rb, rspec-puppet.gemspec, spec/classes/test_windows_spec.rb, spec/spec_helper.rb, spec/spec_helper_unit.rb, spec/unit/matchers/count_generic_spec.rb, spec/unit/matchers/include_class_spec.rb, spec/unit/matchers/run_spec.rb
Ruby 1 support was already dropped, but some code remained. By now we can assume everyone has migrated to RSpec 3 so dropping compatibility with RSpec 2 is safe. It may not even run on Ruby 2.7.
=> Drop RSpec 2 & Ruby 1 compatiblity

README.md
trusted_server_facts config setting was removed in Puppet 6.x and from rspec-puppet in https://github.com/puppetlabs/rspec-puppet/pull/73.
trusted_node_data was also removed in puppet 4.x+ and from rspec-puppet in https://github.com/puppetlabs/rspec-puppet/pull/73.
This removes the now irrelevant readme sections.
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (maint) - remove irrelevant readme sections

rspec-puppet.gemspec
Updates the naming of the gem on rubygems.org from `rspec-puppet` to `puppetlabs-rspec-puppet`
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (CAT-1235) - Rename to puppetlabs-rspec-puppet

lib/rspec-puppet/example/function_example_group.rb, lib/rspec-puppet/matchers/create_generic.rb, lib/rspec-puppet/matchers/type_matchers.rb, spec/types/valid_provider_spec.rb
Fix rubocop string-to-symbol conversion [nightly CI failures](https://github.com/puppetlabs/rspec-puppet/actions/runs/7080260406/job/19267896863):
```bash
➜  rspec-puppet git:(maint_fix_rubocop_warnings) bundle exec rubocop --format github
::error file=lib/rspec-puppet/example/function_example_group.rb,line=103,col=61::Lint/SymbolConversion: Unnecessary symbol conversion; use `:"function_#{function_name}"` instead.
::error file=lib/rspec-puppet/matchers/create_generic.rb,line=306,col=18::Lint/SymbolConversion: Unnecessary symbol conversion; use `:"eachauto#{type}"` instead.
::error file=lib/rspec-puppet/matchers/type_matchers.rb,line=126,col=28::Lint/SymbolConversion: Unnecessary symbol conversion; use `:"valid#{attr_type}?"` instead.
::error …
```
=> (maint) Fix rubocop lint warnings

lib/rspec-puppet/matchers/dynamic_matchers.rb
This reverts commit a16dc28e02c6fcdb786b719dd12ec5e947bffc14.
Fixes https://github.com/puppetlabs/rspec-puppet/issues/87
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> Revert "(maint) - fix rubocop" - Leading argument with delegation syntax not supported with ruby 2.7.0

spec/unit/adapters_spec.rb
Following the recent introduction of a new cop in Rubocop, Rspec/RemoveConst, our CI has started failing. It seems like this rule is being enforced as a good practice to avoid buggy debug information but no real alternative is being offered.
This commit disables the cop to allow the CI to continue working. Here are the discussions that led to the creation of the rule: 
https://github.com/rubocop/rubocop-rspec/issues/1748 
https://github.com/rubocop/rubocop-rspec/pull/1749
=> (MAINT) Disable new Rspec/RemoveConst cop

rspec-puppet.gemspec
Prior to this PR, the LICENSE file was not shipped with our built gem.
This PR corrects the filename in the gemspec, so that the LICENSE file is now packaged with the gem once built.
Add any additional context about the problem here. 
Fixes https://github.com/puppetlabs/rspec-puppet/issues/107
=> (bug) - Add license file to built gem

lib/rspec-puppet/matchers/parameter_matcher.rb, lib/rspec-puppet/sensitive.rb, spec/unit/matchers/parameter_matcher_spec.rb
When sensitive values are compared and do not match, the produce error message does not help for debugging:
```
1) postgresql::server::role with Password Datatype Sensitive[String] has alter role for "test" user with password as ****
Failure/Error:
is_expected.to contain_postgresql_psql('ALTER ROLE test ENCRYPTED PASSWORD ****')
.with('command'     => sensitive('ALTER ROLE "test" ENCRYPTED PASSWORD \'new-pa$s\''),
'sensitive'   => 'true',
'unless'      => sensitive("SELECT 1 FROM pg_shadow WHERE usename = 'test' AND passwd = 'new-pa$s'"),
'port'        => '5432')
expected that the catalogue would contain Postgresql_psql[ALTER ROLE test ENCRYPTED PASSWORD ****] with command set to Sensitive("ALTER ROLE \"test\" ENCRYPTED PASSWORD 'new-pa$s'") but it is set to #<Sensitive [value redacted]>, …
```
=> Unwrap sensitive values in error messages

README.md
Prior to this commit, the README.md file was not up to date with the latest information on hiera usage.
This commit aims to update the README.md to ensure that users have access to the correct information, based on our documentation.
=> (CAT-1742) Update hiera README

.github/workflows/jekyll-gh-pages.yml, docs/_config.yml, docs/_layouts/base.html, docs/_layouts/cards.html, docs/changelog/index.md, docs/documentation/classes/index.md, docs/documentation/configuration/index.md, docs/documentation/coverage/index.md, docs/documentation/defined_types/index.md, docs/documentation/functions/index.md, docs/documentation/hosts/index.md, docs/documentation/index.md, docs/documentation/setup/index.md, docs/documentation/type_aliases/index.md, docs/documentation/types/index.md, docs/index.html, docs/tutorial/index.md
The jekyll gh-pages action "sources" its documentation from the root "/" of the repository however respec-puppet holds its documentation under a sub-directory `/docs`. This points the action to the correct directory to build the documention from with more advanced configuration options under `/docs/config.yml`. This PR also fixes the issue with the broken links by using Jekyll's global variable `site.url` configured in `/docs/config.yaml`.  The default css theming is expected to be served from the default root directory and ours is `respec-puppet` and the `site.url` is used to fixed this and serve the css from the correct location. 
Mention any related issues or pull requests.
=> Set correct source directory for jekyll gh-action page and add {{ site.ur l}} to fix links and styling

lib/rspec-puppet/support.rb, spec/classes/server_facts_spec.rb
structured facts are around since some years and the legacy facts are deprecated. The current releases causes a lot of `Could not retrieve fact ipaddress` warnings during CI run.
=> server_facts: Switch from legacy to structured facts
